# Generated by Django 4.2.4 on 2023-08-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification_app", "0003_message_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="detail",
            field=models.TextField(default="NO DETAIL"),
            preserve_default=False,
        ),
    ]
